target = "https://www.rfc-editor.org/rfc/rfc8439#section-2.3"

# The ChaCha20 Block Function
#
#    The ChaCha block function transforms a ChaCha state by running
#    multiple quarter rounds.
# 
#    The inputs to ChaCha20 are:
# 
#    o  A 256-bit key, treated as a concatenation of eight 32-bit little-
#       endian integers.
# 
#    o  A 96-bit nonce, treated as a concatenation of three 32-bit little-
#       endian integers.
# 
#    o  A 32-bit block count parameter, treated as a 32-bit little-endian
#       integer.
# 
#    The output is 64 random-looking bytes.
# 
#    The ChaCha algorithm described here uses a 256-bit key.  The original
#    algorithm also specified 128-bit keys and 8- and 12-round variants,
#    but these are out of scope for this document.  In this section, we
#    describe the ChaCha block function.
# 
#    Note also that the original ChaCha had a 64-bit nonce and 64-bit
#    block count.  We have modified this here to be more consistent with
#    recommendations in Section 3.2 of [RFC5116].  This limits the use of
#    a single (key,nonce) combination to 2^32 blocks, or 256 GB, but that
#    is enough for most uses.  In cases where a single key is used by
#    multiple senders, it is important to make sure that they don't use
#    the same nonces.  This can be assured by partitioning the nonce space
#    so that the first 32 bits are unique per sender, while the other 64
#    bits come from a counter.
# 
#    The ChaCha20 state is initialized as follows:
# 
#    o  The first four words (0-3) are constants: 0x61707865, 0x3320646e,
#       0x79622d32, 0x6b206574.
# 
#    o  The next eight words (4-11) are taken from the 256-bit key by
#       reading the bytes in little-endian order, in 4-byte chunks.
# 
#    o  Word 12 is a block counter.  Since each block is 64-byte, a 32-bit
#       word is enough for 256 gigabytes of data.
# 
#    o  Words 13-15 are a nonce, which MUST not be repeated for the same
#       key.  The 13th word is the first 32 bits of the input nonce taken
#       as a little-endian integer, while the 15th word is the last 32
#       bits.
# 
#        cccccccc  cccccccc  cccccccc  cccccccc
#        kkkkkkkk  kkkkkkkk  kkkkkkkk  kkkkkkkk
#        kkkkkkkk  kkkkkkkk  kkkkkkkk  kkkkkkkk
#        bbbbbbbb  nnnnnnnn  nnnnnnnn  nnnnnnnn
# 
#    c=constant k=key b=blockcount n=nonce
# 
#    ChaCha20 runs 20 rounds, alternating between "column rounds" and
#    "diagonal rounds".  Each round consists of four quarter-rounds, and
#    they are run as follows.  Quarter rounds 1-4 are part of a "column"
#    round, while 5-8 are part of a "diagonal" round:
# 
#       QUARTERROUND(0, 4, 8, 12)
#       QUARTERROUND(1, 5, 9, 13)
#       QUARTERROUND(2, 6, 10, 14)
#       QUARTERROUND(3, 7, 11, 15)
#       QUARTERROUND(0, 5, 10, 15)
#       QUARTERROUND(1, 6, 11, 12)
#       QUARTERROUND(2, 7, 8, 13)
#       QUARTERROUND(3, 4, 9, 14)
# 
#    At the end of 20 rounds (or 10 iterations of the above list), we add
#    the original input words to the output words, and serialize the
#    result by sequencing the words one-by-one in little-endian order.
# 
#    Note: "addition" in the above paragraph is done modulo 2^32.  In some
#    machine languages, this is called carryless addition on a 32-bit
#    word.

[[spec]]
level = "MUST"
quote = '''
o  Words 13-15 are a nonce, which MUST not be repeated for the same
key.
'''

