target = "https://www.rfc-editor.org/rfc/rfc8439#section-2.6"

# Generating the Poly1305 Key Using ChaCha20
#
#    As said in Section 2.5, it is acceptable to generate the one-time
#    Poly1305 key pseudorandomly.  This section defines such a method.
# 
#    To generate such a key pair (r,s), we will use the ChaCha20 block
#    function described in Section 2.3.  This assumes that we have a
#    256-bit session key specifically for the Message Authentication Code
#    (MAC) function.  Any document that specifies the use of Poly1305 as a
#    MAC algorithm for some protocol MUST specify that 256 bits are
#    allocated for the integrity key.  Note that in the AEAD construction
#    defined in Section 2.8, the same key is used for encryption and key
#    generation.
# 
#    The method is to call the block function with the following
#    parameters:
# 
#    o  The 256-bit session integrity key is used as the ChaCha20 key.
# 
#    o  The block counter is set to zero.
# 
#    o  The protocol will specify a 96-bit or 64-bit nonce.  This MUST be
#       unique per invocation with the same key, so it MUST NOT be
#       randomly generated.  A counter is a good way to implement this,
#       but other methods, such as a Linear Feedback Shift Register (LFSR)
#       are also acceptable.  ChaCha20 as specified here requires a 96-bit
#       nonce.  So if the provided nonce is only 64-bit, then the first 32
#       bits of the nonce will be set to a constant number.  This will
#       usually be zero, but for protocols with multiple senders it may be
#       different for each sender, but SHOULD be the same for all
#       invocations of the function with the same key by a particular
#       sender.
# 
#    After running the block function, we have a 512-bit state.  We take
#    the first 256 bits of the serialized state, and use those as the one-
#    time Poly1305 key: the first 128 bits are clamped and form "r", while
#    the next 128 bits become "s".  The other 256 bits are discarded.
# 
#    Note that while many protocols have provisions for a nonce for
#    encryption algorithms (often called Initialization Vectors, or IVs),
#    they usually don't have such a provision for the MAC function.  In
#    that case, the per-invocation nonce will have to come from somewhere
#    else, such as a message counter.

[[spec]]
level = "MUST"
quote = '''
Any document that specifies the use of Poly1305 as a
MAC algorithm for some protocol MUST specify that 256 bits are
allocated for the integrity key.
'''

[[spec]]
level = "MUST"
quote = '''
This MUST be
unique per invocation with the same key, so it MUST NOT be
randomly generated.
'''

[[spec]]
level = "SHOULD"
quote = '''
This will
usually be zero, but for protocols with multiple senders it may be
different for each sender, but SHOULD be the same for all
invocations of the function with the same key by a particular
sender.
'''

