target = "https://www.rfc-editor.org/rfc/rfc5280#section-4.2.2.2"

# Subject Information Access
#
#    The subject information access extension indicates how to access
#    information and services for the subject of the certificate in which
#    the extension appears.  When the subject is a CA, information and
#    services may include certificate validation services and CA policy
#    data.  When the subject is an end entity, the information describes
#    the type of services offered and how to access them.  In this case,
#    the contents of this extension are defined in the protocol
# 
#    specifications for the supported services.  This extension may be
#    included in end entity or CA certificates.  Conforming CAs MUST mark
#    this extension as non-critical.
# 
#    id-pe-subjectInfoAccess OBJECT IDENTIFIER ::= { id-pe 11 }
# 
#    SubjectInfoAccessSyntax  ::=
#            SEQUENCE SIZE (1..MAX) OF AccessDescription
# 
#    AccessDescription  ::=  SEQUENCE {
#            accessMethod          OBJECT IDENTIFIER,
#            accessLocation        GeneralName  }
# 
#    Each entry in the sequence SubjectInfoAccessSyntax describes the
#    format and location of additional information provided by the subject
#    of the certificate in which this extension appears.  The type and
#    format of the information are specified by the accessMethod field;
#    the accessLocation field specifies the location of the information.
#    The retrieval mechanism may be implied by the accessMethod or
#    specified by accessLocation.
# 
#    This profile defines one access method to be used when the subject is
#    a CA and one access method to be used when the subject is an end
#    entity.  Additional access methods may be defined in the future in
#    the protocol specifications for other services.
# 
#    The id-ad-caRepository OID is used when the subject is a CA that
#    publishes certificates it issues in a repository.  The accessLocation
#    field is defined as a GeneralName, which can take several forms.
# 
#    When the accessLocation is a directoryName, the information is to be
#    obtained by the application from whatever directory server is locally
#    configured.  When the extension is used to point to CA certificates,
#    the entry for the directoryName contains CA certificates in the
#    crossCertificatePair and/or cACertificate attributes as specified in
#    [RFC4523].  The protocol the application uses to access the directory
#    (e.g., DAP or LDAP) is a local matter.
# 
#    Where the information is available via LDAP, the accessLocation
#    SHOULD be a uniformResourceIdentifier.  The LDAP URI [RFC4516] MUST
#    include a <dn> field containing the distinguished name of the entry
#    holding the certificates, MUST include an <attributes> field that
#    lists appropriate attribute descriptions for the attributes that hold
#    the DER encoded certificates or cross-certificate pairs [RFC4523],
#    and SHOULD include a <host> (e.g., <ldap://ldap.example.com/cn=CA,
#    dc=example,dc=com?cACertificate;binary,crossCertificatePair;binary>).
# 
#    Omitting the <host> (e.g., <ldap:///cn=exampleCA,dc=example,dc=com?
#    cACertificate;binary>) has the effect of relying on whatever a priori
#    knowledge the client might have to contact an appropriate server.
# 
#    Where the information is available via HTTP or FTP, accessLocation
#    MUST be a uniformResourceIdentifier and the URI MUST point to either
#    a single DER encoded certificate as specified in [RFC2585] or a
#    collection of certificates in a BER or DER encoded "certs-only" CMS
#    message as specified in [RFC2797].
# 
#    Conforming applications that support HTTP or FTP for accessing
#    certificates MUST be able to accept individual DER encoded
#    certificates and SHOULD be able to accept "certs-only" CMS messages.
# 
#    HTTP server implementations accessed via the URI SHOULD specify the
#    media type application/pkix-cert [RFC2585] in the content-type header
#    field of the response for a single DER encoded certificate and SHOULD
#    specify the media type application/pkcs7-mime [RFC2797] in the
#    content-type header field of the response for "certs-only" CMS
#    messages.  For FTP, the name of a file that contains a single DER
#    encoded certificate SHOULD have a suffix of ".cer" [RFC2585] and the
#    name of a file that contains a "certs-only" CMS message SHOULD have a
#    suffix of ".p7c" [RFC2797].  Consuming clients may use the media type
#    or file extension as a hint to the content, but should not depend
#    solely on the presence of the correct media type or file extension in
#    the server response.
# 
#    The semantics of other id-ad-caRepository accessLocation name forms
#    are not defined.
# 
#    A subjectInfoAccess extension may include multiple instances of the
#    id-ad-caRepository accessMethod.  The different instances may specify
#    different methods for accessing the same information or may point to
#    different information.  When the id-ad-caRepository accessMethod is
#    used, at least one instance SHOULD specify an accessLocation that is
#    an HTTP [RFC2616] or LDAP [RFC4516] URI.
# 
#    The id-ad-timeStamping OID is used when the subject offers
#    timestamping services using the Time Stamp Protocol defined in
#    [RFC3161].  Where the timestamping services are available via HTTP or
#    FTP, accessLocation MUST be a uniformResourceIdentifier.  Where the
#    timestamping services are available via electronic mail,
#    accessLocation MUST be an rfc822Name.  Where timestamping services
#    are available using TCP/IP, the dNSName or iPAddress name forms may
#    be used.  The semantics of other name forms of accessLocation (when
#    accessMethod is id-ad-timeStamping) are not defined by this
#    specification.
# 
#    Additional access descriptors may be defined in other PKIX
#    specifications.
# 
#    id-ad OBJECT IDENTIFIER ::= { id-pkix 48 }
# 
#    id-ad-caRepository OBJECT IDENTIFIER ::= { id-ad 5 }
# 
#    id-ad-timeStamping OBJECT IDENTIFIER ::= { id-ad 3 }

[[spec]]
level = "MUST"
quote = '''
Conforming CAs MUST mark
this extension as non-critical.
'''

[[spec]]
level = "MUST"
quote = '''
The LDAP URI [RFC4516] MUST
include a <dn> field containing the distinguished name of the entry
holding the certificates, MUST include an <attributes> field that
lists appropriate attribute descriptions for the attributes that hold
the DER encoded certificates or cross-certificate pairs [RFC4523],
and SHOULD include a <host> (e.g., <ldap://ldap.example.com/cn=CA,
dc=example,dc=com?cACertificate;binary,crossCertificatePair;binary>).
'''

[[spec]]
level = "SHOULD"
quote = '''
Where the information is available via LDAP, the accessLocation
SHOULD be a uniformResourceIdentifier.
'''

[[spec]]
level = "MUST"
quote = '''
The LDAP URI [RFC4516] MUST
include a <dn> field containing the distinguished name of the entry
holding the certificates, MUST include an <attributes> field that
lists appropriate attribute descriptions for the attributes that hold
the DER encoded certificates or cross-certificate pairs [RFC4523],
and SHOULD include a <host> (e.g., <ldap://ldap.example.com/cn=CA,
dc=example,dc=com?cACertificate;binary,crossCertificatePair;binary>).
'''

[[spec]]
level = "MUST"
quote = '''
Where the information is available via HTTP or FTP, accessLocation
MUST be a uniformResourceIdentifier and the URI MUST point to either
a single DER encoded certificate as specified in [RFC2585] or a
collection of certificates in a BER or DER encoded "certs-only" CMS
message as specified in [RFC2797].
'''

[[spec]]
level = "MUST"
quote = '''
Where the information is available via HTTP or FTP, accessLocation
MUST be a uniformResourceIdentifier and the URI MUST point to either
a single DER encoded certificate as specified in [RFC2585] or a
collection of certificates in a BER or DER encoded "certs-only" CMS
message as specified in [RFC2797].
'''

[[spec]]
level = "MUST"
quote = '''
Conforming applications that support HTTP or FTP for accessing
certificates MUST be able to accept individual DER encoded
certificates and SHOULD be able to accept "certs-only" CMS messages.
'''

[[spec]]
level = "SHOULD"
quote = '''
HTTP server implementations accessed via the URI SHOULD specify the
media type application/pkix-cert [RFC2585] in the content-type header
field of the response for a single DER encoded certificate and SHOULD
specify the media type application/pkcs7-mime [RFC2797] in the
content-type header field of the response for "certs-only" CMS
messages.
'''

[[spec]]
level = "SHOULD"
quote = '''
HTTP server implementations accessed via the URI SHOULD specify the
media type application/pkix-cert [RFC2585] in the content-type header
field of the response for a single DER encoded certificate and SHOULD
specify the media type application/pkcs7-mime [RFC2797] in the
content-type header field of the response for "certs-only" CMS
messages.
'''

[[spec]]
level = "SHOULD"
quote = '''
For FTP, the name of a file that contains a single DER
encoded certificate SHOULD have a suffix of ".cer" [RFC2585] and the
name of a file that contains a "certs-only" CMS message SHOULD have a
suffix of ".p7c" [RFC2797].
'''

[[spec]]
level = "SHOULD"
quote = '''
For FTP, the name of a file that contains a single DER
encoded certificate SHOULD have a suffix of ".cer" [RFC2585] and the
name of a file that contains a "certs-only" CMS message SHOULD have a
suffix of ".p7c" [RFC2797].
'''

[[spec]]
level = "SHOULD"
quote = '''
When the id-ad-caRepository accessMethod is
used, at least one instance SHOULD specify an accessLocation that is
an HTTP [RFC2616] or LDAP [RFC4516] URI.
'''

[[spec]]
level = "MUST"
quote = '''
Where the timestamping services are available via HTTP or
FTP, accessLocation MUST be a uniformResourceIdentifier.
'''

[[spec]]
level = "MUST"
quote = '''
Where the
timestamping services are available via electronic mail,
accessLocation MUST be an rfc822Name.
'''

