target = "https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.2"

# Serial Number
#
#    The serial number MUST be a positive integer assigned by the CA to
#    each certificate.  It MUST be unique for each certificate issued by a
#    given CA (i.e., the issuer name and serial number identify a unique
#    certificate).  CAs MUST force the serialNumber to be a non-negative
#    integer.
# 
#    Given the uniqueness requirements above, serial numbers can be
#    expected to contain long integers.  Certificate users MUST be able to
#    handle serialNumber values up to 20 octets.  Conforming CAs MUST NOT
#    use serialNumber values longer than 20 octets.
# 
#    Note: Non-conforming CAs may issue certificates with serial numbers
#    that are negative or zero.  Certificate users SHOULD be prepared to
#    gracefully handle such certificates.

[[spec]]
level = "MUST"
quote = '''
The serial number MUST be a positive integer assigned by the CA to
each certificate.
'''

[[spec]]
level = "MUST"
quote = '''
It MUST be unique for each certificate issued by a
given CA (i.e., the issuer name and serial number identify a unique
certificate).
'''

[[spec]]
level = "MUST"
quote = '''
CAs MUST force the serialNumber to be a non-negative
integer.
'''

[[spec]]
level = "MUST"
quote = '''
Certificate users MUST be able to
handle serialNumber values up to 20 octets.
'''

[[spec]]
level = "MUST"
quote = '''
Conforming CAs MUST NOT
use serialNumber values longer than 20 octets.
'''

[[spec]]
level = "SHOULD"
quote = '''
Certificate users SHOULD be prepared to
gracefully handle such certificates.
'''

