target = "https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.7"

# Issuer Alternative Name
#
#    As with Section 4.2.1.6, this extension is used to associate Internet
#    style identities with the certificate issuer.  Issuer alternative
#    name MUST be encoded as in 4.2.1.6.  Issuer alternative names are not
#    processed as part of the certification path validation algorithm in
#    Section 6.  (That is, issuer alternative names are not used in name
#    chaining and name constraints are not enforced.)
# 
#    Where present, conforming CAs SHOULD mark this extension as non-
#    critical.
# 
#    id-ce-issuerAltName OBJECT IDENTIFIER ::=  { id-ce 18 }
# 
#    IssuerAltName ::= GeneralNames

[[spec]]
level = "MUST"
quote = '''
Issuer alternative
name MUST be encoded as in 4.2.1.6.
'''

[[spec]]
level = "SHOULD"
quote = '''
Where present, conforming CAs SHOULD mark this extension as non-
critical.
'''

