target = "https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.9"

# Basic Constraints
#
#    The basic constraints extension identifies whether the subject of the
#    certificate is a CA and the maximum depth of valid certification
#    paths that include this certificate.
# 
#    The cA boolean indicates whether the certified public key may be used
#    to verify certificate signatures.  If the cA boolean is not asserted,
#    then the keyCertSign bit in the key usage extension MUST NOT be
#    asserted.  If the basic constraints extension is not present in a
#    version 3 certificate, or the extension is present but the cA boolean
#    is not asserted, then the certified public key MUST NOT be used to
#    verify certificate signatures.
# 
#    The pathLenConstraint field is meaningful only if the cA boolean is
#    asserted and the key usage extension, if present, asserts the
#    keyCertSign bit (Section 4.2.1.3).  In this case, it gives the
#    maximum number of non-self-issued intermediate certificates that may
#    follow this certificate in a valid certification path.  (Note: The
#    last certificate in the certification path is not an intermediate
#    certificate, and is not included in this limit.  Usually, the last
#    certificate is an end entity certificate, but it can be a CA
#    certificate.)  A pathLenConstraint of zero indicates that no non-
#    self-issued intermediate CA certificates may follow in a valid
#    certification path.  Where it appears, the pathLenConstraint field
#    MUST be greater than or equal to zero.  Where pathLenConstraint does
#    not appear, no limit is imposed.
# 
#    Conforming CAs MUST include this extension in all CA certificates
#    that contain public keys used to validate digital signatures on
#    certificates and MUST mark the extension as critical in such
#    certificates.  This extension MAY appear as a critical or non-
#    critical extension in CA certificates that contain public keys used
#    exclusively for purposes other than validating digital signatures on
#    certificates.  Such CA certificates include ones that contain public
#    keys used exclusively for validating digital signatures on CRLs and
#    ones that contain key management public keys used with certificate
# 
#    enrollment protocols.  This extension MAY appear as a critical or
#    non-critical extension in end entity certificates.
# 
#    CAs MUST NOT include the pathLenConstraint field unless the cA
#    boolean is asserted and the key usage extension asserts the
#    keyCertSign bit.
# 
#    id-ce-basicConstraints OBJECT IDENTIFIER ::=  { id-ce 19 }
# 
#    BasicConstraints ::= SEQUENCE {
#         cA                      BOOLEAN DEFAULT FALSE,
#         pathLenConstraint       INTEGER (0..MAX) OPTIONAL }

[[spec]]
level = "MUST"
quote = '''
If the cA boolean is not asserted,
then the keyCertSign bit in the key usage extension MUST NOT be
asserted.
'''

[[spec]]
level = "MUST"
quote = '''
If the basic constraints extension is not present in a
version 3 certificate, or the extension is present but the cA boolean
is not asserted, then the certified public key MUST NOT be used to
verify certificate signatures.
'''

[[spec]]
level = "MUST"
quote = '''
Where it appears, the pathLenConstraint field
MUST be greater than or equal to zero.
'''

[[spec]]
level = "MUST"
quote = '''
Conforming CAs MUST include this extension in all CA certificates
that contain public keys used to validate digital signatures on
certificates and MUST mark the extension as critical in such
certificates.
'''

[[spec]]
level = "MUST"
quote = '''
Conforming CAs MUST include this extension in all CA certificates
that contain public keys used to validate digital signatures on
certificates and MUST mark the extension as critical in such
certificates.
'''

[[spec]]
level = "MAY"
quote = '''
This extension MAY appear as a critical or non-
critical extension in CA certificates that contain public keys used
exclusively for purposes other than validating digital signatures on
certificates.
'''

[[spec]]
level = "MAY"
quote = '''
This extension MAY appear as a critical or
non-critical extension in end entity certificates.
'''

[[spec]]
level = "MUST"
quote = '''
CAs MUST NOT include the pathLenConstraint field unless the cA
boolean is asserted and the key usage extension asserts the
keyCertSign bit.
'''

[[spec]]
level = "MAY"
quote = '''
.MAX) OPTIONAL }
'''

