target = "https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.5"

# Validity
#
#    The certificate validity period is the time interval during which the
#    CA warrants that it will maintain information about the status of the
#    certificate.  The field is represented as a SEQUENCE of two dates:
#    the date on which the certificate validity period begins (notBefore)
#    and the date on which the certificate validity period ends
#    (notAfter).  Both notBefore and notAfter may be encoded as UTCTime or
#    GeneralizedTime.
# 
#    CAs conforming to this profile MUST always encode certificate
#    validity dates through the year 2049 as UTCTime; certificate validity
#    dates in 2050 or later MUST be encoded as GeneralizedTime.
#    Conforming applications MUST be able to process validity dates that
#    are encoded in either UTCTime or GeneralizedTime.
# 
#    The validity period for a certificate is the period of time from
#    notBefore through notAfter, inclusive.
# 
#    In some situations, devices are given certificates for which no good
#    expiration date can be assigned.  For example, a device could be
#    issued a certificate that binds its model and serial number to its
#    public key; such a certificate is intended to be used for the entire
#    lifetime of the device.
# 
#    To indicate that a certificate has no well-defined expiration date,
#    the notAfter SHOULD be assigned the GeneralizedTime value of
#    99991231235959Z.
# 
#    When the issuer will not be able to maintain status information until
#    the notAfter date (including when the notAfter date is
#    99991231235959Z), the issuer MUST ensure that no valid certification
#    path exists for the certificate after maintenance of status
# 
#    information is terminated.  This may be accomplished by expiration or
#    revocation of all CA certificates containing the public key used to
#    verify the signature on the certificate and discontinuing use of the
#    public key used to verify the signature on the certificate as a trust
#    anchor.

[[spec]]
level = "MUST"
quote = '''
CAs conforming to this profile MUST always encode certificate
validity dates through the year 2049 as UTCTime; certificate validity
dates in 2050 or later MUST be encoded as GeneralizedTime.
'''

[[spec]]
level = "MUST"
quote = '''
CAs conforming to this profile MUST always encode certificate
validity dates through the year 2049 as UTCTime; certificate validity
dates in 2050 or later MUST be encoded as GeneralizedTime.
'''

[[spec]]
level = "MUST"
quote = '''
Conforming applications MUST be able to process validity dates that
are encoded in either UTCTime or GeneralizedTime.
'''

[[spec]]
level = "SHOULD"
quote = '''
To indicate that a certificate has no well-defined expiration date,
the notAfter SHOULD be assigned the GeneralizedTime value of
99991231235959Z.
'''

[[spec]]
level = "MUST"
quote = '''
When the issuer will not be able to maintain status information until
the notAfter date (including when the notAfter date is
99991231235959Z), the issuer MUST ensure that no valid certification
path exists for the certificate after maintenance of status
'''

