target = "https://www.rfc-editor.org/rfc/rfc5280#section-5.1.2.6"

# Revoked Certificates
#
#    When there are no revoked certificates, the revoked certificates list
#    MUST be absent.  Otherwise, revoked certificates are listed by their
#    serial numbers.  Certificates revoked by the CA are uniquely
#    identified by the certificate serial number.  The date on which the
#    revocation occurred is specified.  The time for revocationDate MUST
#    be expressed as described in Section 5.1.2.4.  Additional information
#    may be supplied in CRL entry extensions; CRL entry extensions are
#    discussed in Section 5.3.

[[spec]]
level = "MUST"
quote = '''
When there are no revoked certificates, the revoked certificates list
MUST be absent.
'''

[[spec]]
level = "MUST"
quote = '''
The time for revocationDate MUST
be expressed as described in Section 5.1.2.4.
'''

