target = "https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.15"

# Freshest CRL (a.k.a. Delta CRL Distribution Point)
#
#    The freshest CRL extension identifies how delta CRL information is
#    obtained.  The extension MUST be marked as non-critical by conforming
#    CAs.  Further discussion of CRL management is contained in Section 5.
# 
#    The same syntax is used for this extension and the
#    cRLDistributionPoints extension, and is described in Section
#    4.2.1.13.  The same conventions apply to both extensions.
# 
#    id-ce-freshestCRL OBJECT IDENTIFIER ::=  { id-ce 46 }
# 
#    FreshestCRL ::= CRLDistributionPoints

[[spec]]
level = "MUST"
quote = '''
The extension MUST be marked as non-critical by conforming
CAs.
'''

