target = "https://www.rfc-editor.org/rfc/rfc3394#section-5"

# Security Considerations
#
#    The key wrap algorithm includes a strong integrity check on the key
#    data.  If unwrapping produces the expected check value in A[0], then
#    the chance that the key data is corrupt is 2^-64.  If unwrapping
#    produces an unexpected value, then the algorithm implementation MUST
#    return an error, and it MUST NOT return any key data.
# 
#    Implementations must protect the KEK from disclosure.  Compromise of
#    the KEK may result in the disclosure of all key data protected with
#    that KEK.

[[spec]]
level = "MUST"
quote = '''
If unwrapping
produces an unexpected value, then the algorithm implementation MUST
return an error, and it MUST NOT return any key data.
'''

